### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by thecodeduchess** [astridj/prj-rev-bwfs-dasmoto#1]
https://github.com/astridj/prj-rev-bwfs-dasmoto/blob/008194e12e69f49e9d21dbc7bf4c34e6853cc4e2/Dasmoto/index.html#L13

In the future, you will learn how to host these picture files and resources locally within your project.
The benefit of that is, your project will always be online if the site hosting your images is down.

**Comment by astridj** [comment]
Got it, thanks!
